[project]
name = "blank-app-template"
version = "0.1.0"
description = "A simple Streamlit app template."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "streamlit>=1.42,<2",
    "pandas",
    "openpyxl",
    "ortools",
    "xlsxwriter",
    "streamlit-cookies-controller==0.0.4",
]

[tool.uv]
package = false
